# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myurlshortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlkey',
            options={'ordering': ['is_assigned', 'key_name'], 'verbose_name': 'Url Key', 'verbose_name_plural': 'Url Keys'},
        ),
    ]
