# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myurlshortner', '0002_auto_20170519_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlkey',
            name='is_assigned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='urlkey',
            name='key_name',
            field=models.CharField(db_index=True, max_length=500, unique=True),
        ),
    ]
