# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myurlshortner', '0003_auto_20170519_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlkey',
            name='key_name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
